export const chart1114 = {
  url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A1114%7D&dashboard_id=74`,
  payload: {
    datasource: {
      id: 321,
      type: "table",
    },
    force: false,
    form_data: {
      adhoc_filters: [
        {
          clause: "WHERE",
          comparator: "45",
          datasourceWarning: false,
          expressionType: "SIMPLE",
          filterOptionName: "filter_4hxczqbj1k9_9x2fcgxt2hc",
          isExtra: false,
          isNew: false,
          operator: "<",
          operatorId: "LESS_THAN",
          sqlExpression: null,
          subject: "content_score",
        },
        {
          clause: "WHERE",
          comparator: "No filter",
          datasourceWarning: false,
          expressionType: "SIMPLE",
          filterOptionName: "filter_mcbxhyfrplb_yepb969144",
          isExtra: true,
          isNew: false,
          operator: "TEMPORAL_RANGE",
          sqlExpression: null,
          subject: "date",
        },
      ],
      all_columns: [],
      allow_render_html: true,
      chart_id: 1114,
      color_pn: true,
      comparison_color_scheme: "Green",
      comparison_type: "values",
      dashboards: [74],
      datasource: "321__table",
      extra_filters: [],
      extra_form_data: {
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
        ],
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
      },
      force: false,
      groupby: ["program_name", "channel_name_tvd", "time_group", "typo_first"],
      label_colors: {},
      map_label_colors: {
        "AVG(arr_score)": "#666666",
        "AVG(content_score)": "#FF7F44",
        "AVG(lead_in_score)": "#1FA8C9",
        "AVG(ovr_score)": "#FCC700",
        "AVG(reach_score)": "#E04355",
        "AVG(rvr_score)": "#454E7C",
        "AVG(wte_score)": "#5AC189",
        "COUNT(content_score_category)": "#1FA8C9",
        "COUNT(slot_score_category)": "#1FA8C9",
      },
      metrics: [
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "content_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 8068,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(content_score)",
          optionName: "metric_52qg9mu7wz_63ixlvs52ir",
          sqlExpression: null,
        },
      ],
      order_by_cols: [],
      order_desc: false,
      percent_metrics: [],
      query_mode: "aggregate",
      result_format: "json",
      result_type: "full",
      row_limit: 10000,
      server_page_length: 10,
      shared_label_colors: [],
      show_cell_bars: true,
      slice_id: 1114,
      table_timestamp_format: "smart_date",
      temporal_columns_lookup: {
        date: true,
      },
      timeseries_limit_metric: {
        aggregate: "AVG",
        column: {
          advanced_data_type: null,
          certification_details: null,
          certified_by: null,
          column_name: "content_score",
          description: null,
          expression: null,
          filterable: true,
          groupby: true,
          id: 8068,
          is_certified: false,
          is_dttm: false,
          python_date_format: null,
          type: "DOUBLE",
          type_generic: 0,
          verbose_name: null,
          warning_markdown: null,
        },
        datasourceWarning: false,
        expressionType: "SIMPLE",
        hasCustomLabel: false,
        label: "AVG(content_score)",
        optionName: "metric_w1eizdy4gr_7v9fvh2mlfq",
        sqlExpression: null,
      },
      url_params: {},
      viz_type: "table",
    },
    queries: [
      {
        annotation_layers: [],
        applied_time_extras: {},
        columns: [
          "program_name",
          "channel_name_tvd",
          "time_group",
          "typo_first",
        ],
        custom_form_data: {},
        custom_params: {},
        extras: {
          having: "",
          where: "",
        },
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
          {
            col: "content_score",
            op: "<",
            val: "45",
          },
          {
            col: "date",
            op: "TEMPORAL_RANGE",
            val: "No filter",
          },
        ],
        metrics: [
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "content_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 8068,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(content_score)",
            optionName: "metric_52qg9mu7wz_63ixlvs52ir",
            sqlExpression: null,
          },
        ],
        order_desc: false,
        orderby: [
          [
            {
              aggregate: "AVG",
              column: {
                advanced_data_type: null,
                certification_details: null,
                certified_by: null,
                column_name: "content_score",
                description: null,
                expression: null,
                filterable: true,
                groupby: true,
                id: 8068,
                is_certified: false,
                is_dttm: false,
                python_date_format: null,
                type: "DOUBLE",
                type_generic: 0,
                verbose_name: null,
                warning_markdown: null,
              },
              datasourceWarning: false,
              expressionType: "SIMPLE",
              hasCustomLabel: false,
              label: "AVG(content_score)",
              optionName: "metric_w1eizdy4gr_7v9fvh2mlfq",
              sqlExpression: null,
            },
            true,
          ],
        ],
        post_processing: [],
        row_limit: 10000,
        series_limit: 0,
        series_limit_metric: {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "content_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 8068,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(content_score)",
          optionName: "metric_w1eizdy4gr_7v9fvh2mlfq",
          sqlExpression: null,
        },
        time_offsets: [],
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
        url_params: {},
      },
    ],
    result_format: "json",
    result_type: "full",
  },
};
