export const chart1118 = {
  url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A1118%7D&dashboard_id=74`,
  payload: {
    datasource: {
      id: 321,
      type: "table",
    },
    force: false,
    form_data: {
      adhoc_filters: [
        {
          clause: "WHERE",
          comparator: "No filter",
          expressionType: "SIMPLE",
          operator: "TEMPORAL_RANGE",
          subject: "date",
        },
      ],
      annotation_layers: [],
      chart_id: 1118,
      color_scheme: "supersetColors",
      comparison_type: "values",
      dashboards: [118],
      datasource: "321__table",
      extra_filters: [],
      extra_form_data: {
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
        ],
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
      },
      force: false,
      forecastInterval: 0.8,
      forecastPeriods: 10,
      groupby: [],
      label_colors: {},
      legendOrientation: "top",
      legendType: "scroll",
      map_label_colors: {
        "AVG(arr_score)": "#666666",
        "AVG(content_score)": "#FF7F44",
        "AVG(lead_in_score)": "#1FA8C9",
        "AVG(ovr_score)": "#FCC700",
        "AVG(reach_score)": "#E04355",
        "AVG(rvr_score)": "#454E7C",
        "AVG(wte_score)": "#5AC189",
        "COUNT(content_score_category)": "#1FA8C9",
        "COUNT(slot_score_category)": "#1FA8C9",
      },
      markerSize: 6,
      metrics: [
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "content_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 8068,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(content_score)",
          optionName: "metric_v0n5zjofgi_tno4x2hqjb",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "lead_in_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 8053,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(lead_in_score)",
          optionName: "metric_i5wd174lbo_07fkyf684bh3",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "wte_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 8041,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(wte_score)",
          optionName: "metric_nztucsuoyj_c8zy2wmy42f",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "rvr_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 8043,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(rvr_score)",
          optionName: "metric_gfl6l31pggt_oel15jhc10o",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "ovr_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 8045,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(ovr_score)",
          optionName: "metric_r8g24bl3gj9_kylurqpzx9",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "arr_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 8047,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(arr_score)",
          optionName: "metric_4w8ds735exx_yb11ltph17",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "reach_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 8049,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(reach_score)",
          optionName: "metric_i14i0n3gdyb_387lfrvx03q",
          sqlExpression: null,
        },
      ],
      only_total: true,
      opacity: 0.2,
      order_desc: true,
      own_color_scheme: "supersetColors",
      result_format: "json",
      result_type: "full",
      rich_tooltip: true,
      row_limit: 1000,
      seriesType: "line",
      shared_label_colors: [],
      show_empty_columns: true,
      show_legend: true,
      showTooltipPercentage: true,
      showTooltipTotal: true,
      slice_id: 1118,
      sort_series_type: "sum",
      time_shift_color: true,
      tooltipTimeFormat: "smart_date",
      truncate_metric: true,
      truncateXAxis: true,
      url_params: {
        native_filters_key:
          "i1n-Sa6qDM6gfFWzlaDhzTj2XgDqWGqYO8skLct1pUvvu8tf6ZUGLs4b3O7q-LCx",
      },
      viz_type: "echarts_timeseries_line",
      x_axis: "date",
      x_axis_sort_asc: true,
      x_axis_sort_series: "name",
      x_axis_sort_series_ascending: true,
      x_axis_time_format: "smart_date",
      x_axis_title_margin: 15,
      y_axis_bounds: [null, null],
      y_axis_format: "SMART_NUMBER",
      y_axis_title_margin: 15,
      y_axis_title_position: "Left",
    },
    queries: [
      {
        annotation_layers: [],
        applied_time_extras: {},
        columns: [
          {
            columnType: "BASE_AXIS",
            expressionType: "SQL",
            label: "date",
            sqlExpression: "date",
          },
        ],
        custom_form_data: {},
        custom_params: {},
        extras: {
          having: "",
          where: "",
        },
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
          {
            col: "date",
            op: "TEMPORAL_RANGE",
            val: "No filter",
          },
        ],
        metrics: [
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "content_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 8068,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(content_score)",
            optionName: "metric_v0n5zjofgi_tno4x2hqjb",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "lead_in_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 8053,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(lead_in_score)",
            optionName: "metric_i5wd174lbo_07fkyf684bh3",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "wte_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 8041,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(wte_score)",
            optionName: "metric_nztucsuoyj_c8zy2wmy42f",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "rvr_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 8043,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(rvr_score)",
            optionName: "metric_gfl6l31pggt_oel15jhc10o",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "ovr_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 8045,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(ovr_score)",
            optionName: "metric_r8g24bl3gj9_kylurqpzx9",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "arr_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 8047,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(arr_score)",
            optionName: "metric_4w8ds735exx_yb11ltph17",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "reach_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 8049,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(reach_score)",
            optionName: "metric_i14i0n3gdyb_387lfrvx03q",
            sqlExpression: null,
          },
        ],
        order_desc: true,
        orderby: [
          [
            {
              aggregate: "AVG",
              column: {
                advanced_data_type: null,
                certification_details: null,
                certified_by: null,
                column_name: "content_score",
                description: null,
                expression: null,
                filterable: true,
                groupby: true,
                id: 8068,
                is_certified: false,
                is_dttm: false,
                python_date_format: null,
                type: "DOUBLE",
                type_generic: 0,
                verbose_name: null,
                warning_markdown: null,
              },
              datasourceWarning: false,
              expressionType: "SIMPLE",
              hasCustomLabel: false,
              label: "AVG(content_score)",
              optionName: "metric_v0n5zjofgi_tno4x2hqjb",
              sqlExpression: null,
            },
            false,
          ],
        ],
        post_processing: [
          {
            operation: "pivot",
            options: {
              aggregates: {
                "AVG(arr_score)": {
                  operator: "mean",
                },
                "AVG(content_score)": {
                  operator: "mean",
                },
                "AVG(lead_in_score)": {
                  operator: "mean",
                },
                "AVG(ovr_score)": {
                  operator: "mean",
                },
                "AVG(reach_score)": {
                  operator: "mean",
                },
                "AVG(rvr_score)": {
                  operator: "mean",
                },
                "AVG(wte_score)": {
                  operator: "mean",
                },
              },
              columns: [],
              drop_missing_columns: false,
              index: ["date"],
            },
          },
          {
            operation: "flatten",
          },
        ],
        row_limit: 1000,
        series_columns: [],
        series_limit: 0,
        time_offsets: [],
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
        url_params: {
          native_filters_key:
            "i1n-Sa6qDM6gfFWzlaDhzTj2XgDqWGqYO8skLct1pUvvu8tf6ZUGLs4b3O7q-LCx",
        },
      },
    ],
    result_format: "json",
    result_type: "full",
  },
};
