export const chart1126 = {
  url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A1126%7D&dashboard_id=74`,
  payload: {
    datasource: {
      id: 321,
      type: "table",
    },
    force: false,
    form_data: {
      datasource: "321__table",
      viz_type: "table",
      slice_id: 1126,
      url_params: {
        native_filters_key:
          "tmn28MCp4l0hbde4xXiAQcE2Ix-3vQTxRFeT1mhRL_M-5SCotyce2HrvqcLILJvf",
      },
      query_mode: "aggregate",
      groupby: [
        "channel_name_tvd",
        "time_group",
        "dur_group",
        "week_day",
        "typo_first",
      ],
      temporal_columns_lookup: {
        date: true,
      },
      metrics: [
        {
          aggregate: null,
          column: null,
          datasourceWarning: false,
          expressionType: "SQL",
          hasCustomLabel: false,
          label: "count(broadcast_count)",
          optionName: "metric_hpygllu7jhk_i9ev9lo3639",
          sqlExpression: "count(broadcast_count)",
        },
      ],
      all_columns: [],
      percent_metrics: [],
      adhoc_filters: [
        {
          clause: "WHERE",
          comparator: "No filter",
          expressionType: "SIMPLE",
          isExtra: true,
          operator: "TEMPORAL_RANGE",
          subject: "date",
        },
      ],
      order_by_cols: [],
      row_limit: 1000,
      server_page_length: 10,
      order_desc: true,
      table_timestamp_format: "smart_date",
      allow_render_html: true,
      show_cell_bars: true,
      color_pn: true,
      comparison_color_scheme: "Green",
      conditional_formatting: [],
      comparison_type: "values",
      dashboards: [74],
      extra_form_data: {
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
          {
            col: "program_name",
            op: "IN",
            val: ["THỜI SỰ 19H"],
          },
        ],
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
      },
      chart_id: 1126,
      label_colors: {},
      shared_label_colors: [],
      map_label_colors: {
        "COUNT(slot_score_category)": "#1FA8C9",
        "COUNT(content_score_category)": "#1FA8C9",
        "AVG(lead_in_score)": "#1FA8C9",
        "AVG(rvr_score)": "#454E7C",
        "AVG(wte_score)": "#5AC189",
        "AVG(content_score)": "#FF7F44",
        "AVG(arr_score)": "#666666",
        "AVG(reach_score)": "#E04355",
        "AVG(ovr_score)": "#FCC700",
      },
      extra_filters: [],
      force: false,
      result_format: "json",
      result_type: "full",
    },
    queries: [
      {
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
          {
            col: "program_name",
            op: "IN",
            val: ["THỜI SỰ 19H"],
          },
          {
            col: "date",
            op: "TEMPORAL_RANGE",
            val: "No filter",
          },
        ],
        extras: {
          having: "",
          where: "",
        },
        applied_time_extras: {},
        columns: [
          "channel_name_tvd",
          "time_group",
          "dur_group",
          "week_day",
          "typo_first",
        ],
        metrics: [
          {
            aggregate: null,
            column: null,
            datasourceWarning: false,
            expressionType: "SQL",
            hasCustomLabel: false,
            label: "count(broadcast_count)",
            optionName: "metric_hpygllu7jhk_i9ev9lo3639",
            sqlExpression: "count(broadcast_count)",
          },
        ],
        orderby: [
          [
            {
              aggregate: null,
              column: null,
              datasourceWarning: false,
              expressionType: "SQL",
              hasCustomLabel: false,
              label: "count(broadcast_count)",
              optionName: "metric_hpygllu7jhk_i9ev9lo3639",
              sqlExpression: "count(broadcast_count)",
            },
            false,
          ],
        ],
        annotation_layers: [],
        row_limit: 1000,
        series_limit: 0,
        order_desc: true,
        url_params: {
          native_filters_key:
            "tmn28MCp4l0hbde4xXiAQcE2Ix-3vQTxRFeT1mhRL_M-5SCotyce2HrvqcLILJvf",
        },
        custom_params: {},
        custom_form_data: {},
        post_processing: [],
        time_offsets: [],
      },
    ],
    result_format: "json",
    result_type: "full",
  },
};
