export const chart1117 = {
  url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A1117%7D&dashboard_id=74`,
  payload: {
    datasource: {
      id: 321,
      type: "table",
    },
    force: false,
    form_data: {
      datasource: "321__table",
      viz_type: "table",
      slice_id: 1117,
      url_params: {
        native_filters_key:
          "5HxWYPLvKq9NI6vSmPVeTk1Gt8L2AqpDlu6E97RY0Ou59PZfFYiZcy-GoRPFs4Kv",
      },
      query_mode: "aggregate",
      groupby: [],
      temporal_columns_lookup: {
        date: true,
      },
      metrics: [
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "slot_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4298,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(slot_score)",
          optionName: "metric_qulyblkbfk7_ha6kflc4487",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "slot_rating",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4295,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(slot_rating)",
          optionName: "metric_py0r1jstw6g_s7147m0g43q",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "slot_rating_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4279,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(slot_rating_score)",
          optionName: "metric_6pypjjk83dv_c5ybvw7qxq",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "total_unique_viewers",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4325,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "LONGLONG",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(total_unique_viewers)",
          optionName: "metric_0zc2pg5a6yu_wp3ot1eis7h",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "slot_reach_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4273,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(slot_reach_score)",
          optionName: "metric_ycj9jshc1q_btddy8nlkdd",
          sqlExpression: null,
        },
        {
          aggregate: null,
          column: null,
          datasourceWarning: false,
          expressionType: "SQL",
          hasCustomLabel: false,
          label: "AVG(lead_in_effect)*100",
          optionName: "metric_xfktbls8gsc_jmr9l3zt9bp",
          sqlExpression: "AVG(lead_in_effect)*100",
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "lead_in_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4276,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(lead_in_score)",
          optionName: "metric_xprmfor1brj_mwei0cbc80c",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "lead_out_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4277,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(lead_out_score)",
          optionName: "metric_4r0nqb6rnb_4qiepuaouh",
          sqlExpression: null,
        },
        {
          aggregate: null,
          column: null,
          datasourceWarning: false,
          expressionType: "SQL",
          hasCustomLabel: false,
          label: "AVG(lead_out_effect)*100",
          optionName: "metric_xty8boz3mfa_kbijgyteb3",
          sqlExpression: "AVG(lead_out_effect)*100",
        },
      ],
      all_columns: [],
      percent_metrics: [],
      adhoc_filters: [
        {
          clause: "WHERE",
          comparator: "No filter",
          expressionType: "SIMPLE",
          operator: "TEMPORAL_RANGE",
          subject: "date",
        },
      ],
      order_by_cols: [],
      row_limit: 1000,
      server_page_length: 10,
      order_desc: true,
      table_timestamp_format: "smart_date",
      allow_render_html: true,
      show_cell_bars: true,
      color_pn: true,
      comparison_color_scheme: "Green",
      conditional_formatting: [],
      comparison_type: "values",
      dashboards: [74],
      extra_form_data: {
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
          {
            col: "program_name",
            op: "IN",
            val: ["THỜI SỰ 19H"],
          },
        ],
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
      },
      chart_id: 1117,
      label_colors: {},
      shared_label_colors: [],
      map_label_colors: {
        "COUNT(slot_score_category)": "#1FA8C9",
        "COUNT(content_score_category)": "#1FA8C9",
        "AVG(lead_in_score)": "#1FA8C9",
        "AVG(rvr_score)": "#454E7C",
        "AVG(wte_score)": "#5AC189",
        "AVG(content_score)": "#FF7F44",
        "AVG(arr_score)": "#666666",
        "AVG(reach_score)": "#E04355",
        "AVG(ovr_score)": "#FCC700",
      },
      extra_filters: [],
      force: false,
      result_format: "json",
      result_type: "full",
    },
    queries: [
      {
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
          {
            col: "program_name",
            op: "IN",
            val: ["THỜI SỰ 19H"],
          },
          {
            col: "date",
            op: "TEMPORAL_RANGE",
            val: "No filter",
          },
        ],
        extras: {
          having: "",
          where: "",
        },
        applied_time_extras: {},
        columns: [],
        metrics: [
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "slot_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4298,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(slot_score)",
            optionName: "metric_qulyblkbfk7_ha6kflc4487",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "slot_rating",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4295,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(slot_rating)",
            optionName: "metric_py0r1jstw6g_s7147m0g43q",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "slot_rating_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4279,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(slot_rating_score)",
            optionName: "metric_6pypjjk83dv_c5ybvw7qxq",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "total_unique_viewers",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4325,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "LONGLONG",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(total_unique_viewers)",
            optionName: "metric_0zc2pg5a6yu_wp3ot1eis7h",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "slot_reach_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4273,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(slot_reach_score)",
            optionName: "metric_ycj9jshc1q_btddy8nlkdd",
            sqlExpression: null,
          },
          {
            aggregate: null,
            column: null,
            datasourceWarning: false,
            expressionType: "SQL",
            hasCustomLabel: false,
            label: "AVG(lead_in_effect)*100",
            optionName: "metric_xfktbls8gsc_jmr9l3zt9bp",
            sqlExpression: "AVG(lead_in_effect)*100",
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "lead_in_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4276,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(lead_in_score)",
            optionName: "metric_xprmfor1brj_mwei0cbc80c",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "lead_out_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4277,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(lead_out_score)",
            optionName: "metric_4r0nqb6rnb_4qiepuaouh",
            sqlExpression: null,
          },
          {
            aggregate: null,
            column: null,
            datasourceWarning: false,
            expressionType: "SQL",
            hasCustomLabel: false,
            label: "AVG(lead_out_effect)*100",
            optionName: "metric_xty8boz3mfa_kbijgyteb3",
            sqlExpression: "AVG(lead_out_effect)*100",
          },
        ],
        orderby: [
          [
            {
              aggregate: "AVG",
              column: {
                advanced_data_type: null,
                certification_details: null,
                certified_by: null,
                column_name: "slot_score",
                description: null,
                expression: null,
                filterable: true,
                groupby: true,
                id: 4298,
                is_certified: false,
                is_dttm: false,
                python_date_format: null,
                type: "DOUBLE",
                type_generic: 0,
                verbose_name: null,
                warning_markdown: null,
              },
              datasourceWarning: false,
              expressionType: "SIMPLE",
              hasCustomLabel: false,
              label: "AVG(slot_score)",
              optionName: "metric_qulyblkbfk7_ha6kflc4487",
              sqlExpression: null,
            },
            false,
          ],
        ],
        annotation_layers: [],
        row_limit: 1000,
        series_limit: 0,
        order_desc: true,
        url_params: {
          native_filters_key:
            "5HxWYPLvKq9NI6vSmPVeTk1Gt8L2AqpDlu6E97RY0Ou59PZfFYiZcy-GoRPFs4Kv",
        },
        custom_params: {},
        custom_form_data: {},
        post_processing: [],
        time_offsets: [],
      },
    ],
    result_format: "json",
    result_type: "full",
  },
};
