export const chart1112 = {
  url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A1112%7D&dashboard_id=74`,
  payload: {
    datasource: {
      id: 321,
      type: "table",
    },
    force: false,
    form_data: {
      datasource: "321__table",
      viz_type: "table",
      slice_id: 1112,
      url_params: {
        native_filters_key:
          "EAp_thA0tXxd30TIZ33aBsSafPkle2m9bnWJTbLqNmzHgzar97Fz3Ouj7MoIrlIg",
      },
      query_mode: "aggregate",
      groupby: [
        "date",
        "program_name",
        "time_group",
        "channel_name_tvd",
        "content_score",
        "wte_score",
        "arr_score",
        "ovr_score",
        "rvr_score",
        "tsv_score",
        "slot_score",
        "slot_rating_score",
        "lead_in_score",
        "slot_reach_score",
        "lead_out_score",
      ],
      time_grain_sqla: "P1D",
      temporal_columns_lookup: {
        date: true,
      },
      all_columns: [],
      percent_metrics: [],
      adhoc_filters: [
        {
          clause: "WHERE",
          comparator: "No filter",
          expressionType: "SIMPLE",
          operator: "TEMPORAL_RANGE",
          subject: "date",
        },
      ],
      order_by_cols: [],
      row_limit: 1000,
      server_page_length: 10,
      order_desc: true,
      table_timestamp_format: "smart_date",
      allow_render_html: true,
      show_cell_bars: true,
      color_pn: true,
      comparison_color_scheme: "Green",
      comparison_type: "values",
      dashboards: [74],
      extra_form_data: {
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
        ],
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
      },
      chart_id: 1112,
      label_colors: {},
      shared_label_colors: [],
      map_label_colors: {
        "COUNT(slot_score_category)": "#1FA8C9",
        "COUNT(content_score_category)": "#1FA8C9",
        "AVG(lead_in_score)": "#1FA8C9",
        "AVG(rvr_score)": "#454E7C",
        "AVG(wte_score)": "#5AC189",
        "AVG(content_score)": "#FF7F44",
        "AVG(arr_score)": "#666666",
        "AVG(reach_score)": "#E04355",
        "AVG(ovr_score)": "#FCC700",
      },
      extra_filters: [],
      force: false,
      result_format: "json",
      result_type: "full",
    },
    queries: [
      {
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
          {
            col: "date",
            op: "TEMPORAL_RANGE",
            val: "No filter",
          },
        ],
        extras: {
          time_grain_sqla: "P1D",
          having: "",
          where: "",
        },
        applied_time_extras: {},
        columns: [
          {
            timeGrain: "P1D",
            columnType: "BASE_AXIS",
            sqlExpression: "date",
            label: "date",
            expressionType: "SQL",
          },
          "program_name",
          "time_group",
          "channel_name_tvd",
          "content_score",
          "wte_score",
          "arr_score",
          "ovr_score",
          "rvr_score",
          "tsv_score",
          "slot_score",
          "slot_rating_score",
          "lead_in_score",
          "slot_reach_score",
          "lead_out_score",
        ],
        metrics: [],
        orderby: [],
        annotation_layers: [],
        row_limit: 1000,
        series_limit: 0,
        order_desc: true,
        url_params: {
          native_filters_key:
            "EAp_thA0tXxd30TIZ33aBsSafPkle2m9bnWJTbLqNmzHgzar97Fz3Ouj7MoIrlIg",
        },
        custom_params: {},
        custom_form_data: {},
        post_processing: [],
        time_offsets: [],
      },
    ],
    result_format: "json",
    result_type: "full",
  },
};
