export const chart1116 = {
  url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A1116%7D&dashboard_id=74`,
  payload: {
    datasource: {
      id: 321,
      type: "table",
    },
    force: false,
    form_data: {
      adhoc_filters: [
        {
          clause: "WHERE",
          comparator: "No filter",
          expressionType: "SIMPLE",
          operator: "TEMPORAL_RANGE",
          subject: "date",
        },
      ],
      all_columns: [],
      allow_render_html: true,
      annotation_layers: [],
      chart_id: 1116,
      color_pn: true,
      comparison_color_scheme: "Green",
      comparison_type: "values",
      conditional_formatting: [],
      dashboards: [118],
      datasource: "321__table",
      extra_filters: [],
      extra_form_data: {
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
        ],
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
      },
      force: false,
      groupby: [],
      label_colors: {},
      map_label_colors: {
        "AVG(arr_score)": "#666666",
        "AVG(content_score)": "#FF7F44",
        "AVG(lead_in_score)": "#1FA8C9",
        "AVG(ovr_score)": "#FCC700",
        "AVG(reach_score)": "#E04355",
        "AVG(rvr_score)": "#454E7C",
        "AVG(wte_score)": "#5AC189",
        "COUNT(content_score_category)": "#1FA8C9",
        "COUNT(slot_score_category)": "#1FA8C9",
      },
      metrics: [
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "content_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 8068,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(content_score)",
          optionName: "metric_1zhdfx2s8gc_bbfbke3k24t",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "watch_time_efficiency",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 7991,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(watch_time_efficiency)",
          optionName: "metric_tu0yfh30uep_v0c8c3td5t",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "wte_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 8041,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(wte_score)",
          optionName: "metric_6pypjjk83dv_c5ybvw7qxq",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "return_viewer_rate",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 7993,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(return_viewer_rate)",
          optionName: "metric_lfvljv8d2wo_6m3vb3l1d9v",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "rvr_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 8043,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(rvr_score)",
          optionName: "metric_xprmfor1brj_mwei0cbc80c",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "organic_viewer_rate",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 7994,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(organic_viewer_rate)",
          optionName: "metric_e7m68ev3ac_iyw830qlwv",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "ovr_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 8045,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(ovr_score)",
          optionName: "metric_yatldubi5al_oj5tba5yrwo",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "retention_viewer_rate",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 7995,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(retention_viewer_rate)",
          optionName: "metric_f98udldikm_p05am6me26",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "arr_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 8047,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(arr_score)",
          optionName: "metric_4r0nqb6rnb_4qiepuaouh",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "total_unique_viewers_tsv",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 7989,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "LONGLONG",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(total_unique_viewers_tsv)",
          optionName: "metric_tir95jqa12e_4d6zwrckecp",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "tsv_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 8051,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(tsv_score)",
          optionName: "metric_o3vuazcpuy_zi6acb2tnjk",
          sqlExpression: null,
        },
      ],
      order_by_cols: [],
      order_desc: true,
      percent_metrics: [],
      query_mode: "aggregate",
      result_format: "json",
      result_type: "full",
      row_limit: 1000,
      server_page_length: 10,
      shared_label_colors: [],
      show_cell_bars: true,
      slice_id: 1116,
      table_timestamp_format: "smart_date",
      temporal_columns_lookup: {
        date: true,
      },
      url_params: {
        native_filters_key:
          "i1n-Sa6qDM6gfFWzlaDhzTj2XgDqWGqYO8skLct1pUvvu8tf6ZUGLs4b3O7q-LCx",
      },
      viz_type: "table",
    },
    queries: [
      {
        annotation_layers: [],
        applied_time_extras: {},
        columns: [],
        custom_form_data: {},
        custom_params: {},
        extras: {
          having: "",
          where: "",
        },
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
          {
            col: "date",
            op: "TEMPORAL_RANGE",
            val: "No filter",
          },
        ],
        metrics: [
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "content_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 8068,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(content_score)",
            optionName: "metric_1zhdfx2s8gc_bbfbke3k24t",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "watch_time_efficiency",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 7991,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(watch_time_efficiency)",
            optionName: "metric_tu0yfh30uep_v0c8c3td5t",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "wte_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 8041,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(wte_score)",
            optionName: "metric_6pypjjk83dv_c5ybvw7qxq",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "return_viewer_rate",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 7993,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(return_viewer_rate)",
            optionName: "metric_lfvljv8d2wo_6m3vb3l1d9v",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "rvr_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 8043,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(rvr_score)",
            optionName: "metric_xprmfor1brj_mwei0cbc80c",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "organic_viewer_rate",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 7994,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(organic_viewer_rate)",
            optionName: "metric_e7m68ev3ac_iyw830qlwv",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "ovr_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 8045,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(ovr_score)",
            optionName: "metric_yatldubi5al_oj5tba5yrwo",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "retention_viewer_rate",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 7995,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(retention_viewer_rate)",
            optionName: "metric_f98udldikm_p05am6me26",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "arr_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 8047,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(arr_score)",
            optionName: "metric_4r0nqb6rnb_4qiepuaouh",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "total_unique_viewers_tsv",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 7989,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "LONGLONG",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(total_unique_viewers_tsv)",
            optionName: "metric_tir95jqa12e_4d6zwrckecp",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "tsv_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 8051,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(tsv_score)",
            optionName: "metric_o3vuazcpuy_zi6acb2tnjk",
            sqlExpression: null,
          },
        ],
        order_desc: true,
        orderby: [
          [
            {
              aggregate: "AVG",
              column: {
                advanced_data_type: null,
                certification_details: null,
                certified_by: null,
                column_name: "content_score",
                description: null,
                expression: null,
                filterable: true,
                groupby: true,
                id: 8068,
                is_certified: false,
                is_dttm: false,
                python_date_format: null,
                type: "DOUBLE",
                type_generic: 0,
                verbose_name: null,
                warning_markdown: null,
              },
              datasourceWarning: false,
              expressionType: "SIMPLE",
              hasCustomLabel: false,
              label: "AVG(content_score)",
              optionName: "metric_1zhdfx2s8gc_bbfbke3k24t",
              sqlExpression: null,
            },
            false,
          ],
        ],
        post_processing: [],
        row_limit: 1000,
        series_limit: 0,
        time_offsets: [],
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
        url_params: {
          native_filters_key:
            "i1n-Sa6qDM6gfFWzlaDhzTj2XgDqWGqYO8skLct1pUvvu8tf6ZUGLs4b3O7q-LCx",
        },
      },
    ],
    result_format: "json",
    result_type: "full",
  },
};
