export const chart1120 = {
  url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A1120%7D&dashboard_id=74`,
  payload: {
    datasource: {
      id: 321,
      type: "table",
    },
    force: false,
    form_data: {
      datasource: "321__table",
      viz_type: "table",
      slice_id: 1120,
      url_params: {
        native_filters_key:
          "tmn28MCp4l0hbde4xXiAQcE2Ix-3vQTxRFeT1mhRL_M-5SCotyce2HrvqcLILJvf",
      },
      query_mode: "aggregate",
      groupby: ["program_name", "channel_name_tvd", "time_group", "week_day"],
      temporal_columns_lookup: {
        date: true,
      },
      metrics: [
        {
          aggregate: null,
          column: null,
          datasourceWarning: false,
          expressionType: "SQL",
          hasCustomLabel: false,
          label: "count (*)",
          optionName: "metric_35sjruh9oj2_ugrwbdsdew",
          sqlExpression: "count (*)",
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "content_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4296,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(content_score)",
          optionName: "metric_kg0x0215sl_zup80jti3cp",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "wte_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4297,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(wte_score)",
          optionName: "metric_d4fh0nvmbj_b7rhslgjomv",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "rvr_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4300,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(rvr_score)",
          optionName: "metric_fq3ygbzf8bt_9gwgeqaxrk",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "ovr_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4299,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(ovr_score)",
          optionName: "metric_gbtswfejsts_z387kiaai9",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "arr_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4289,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(arr_score)",
          optionName: "metric_69lozuoyu2h_dczm2l8prht",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "tsv_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4301,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(tsv_score)",
          optionName: "metric_amtvfldi4k5_cbyc2td5cjw",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "slot_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4298,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(slot_score)",
          optionName: "metric_v1alya6m7at_9yo0pnhn8um",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "slot_rating_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4279,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(slot_rating_score)",
          optionName: "metric_pvvq9am6mh_6skk4uewiuf",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "slot_reach_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4273,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(slot_reach_score)",
          optionName: "metric_myl4u2rojyg_bi6c5zvv4o",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "lead_in_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4276,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(lead_in_score)",
          optionName: "metric_m46hytb8vh_276o9qe5a0v",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "lead_out_score",
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 4277,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(lead_out_score)",
          optionName: "metric_ju95j2v9uy_8fduwyxvuti",
          sqlExpression: null,
        },
      ],
      all_columns: [],
      percent_metrics: [],
      adhoc_filters: [
        {
          clause: "WHERE",
          comparator: "No filter",
          expressionType: "SIMPLE",
          operator: "TEMPORAL_RANGE",
          subject: "date",
        },
      ],
      timeseries_limit_metric: {
        aggregate: "MAX",
        column: {
          advanced_data_type: null,
          changed_on: "2026-09-15T09:26:30.113179",
          column_name: "content_score",
          created_on: "2026-09-15T09:26:30.113176",
          description: null,
          expression: null,
          extra: '{"warning_markdown":null}',
          filterable: true,
          groupby: true,
          id: 8068,
          is_active: true,
          is_dttm: false,
          python_date_format: null,
          type: "DOUBLE",
          type_generic: 0,
          uuid: "5a521326-e932-4fb2-a435-43753ed5bf20",
          verbose_name: null,
        },
        datasourceWarning: false,
        expressionType: "SIMPLE",
        hasCustomLabel: false,
        label: "MAX(content_score)",
        optionName: "metric_sg01vgonb3_0uobtl8xpbr",
        sqlExpression: null,
      },
      order_by_cols: [],
      row_limit: 1000,
      server_page_length: 10,
      order_desc: false,
      table_timestamp_format: "smart_date",
      include_search: true,
      allow_render_html: true,
      show_cell_bars: true,
      color_pn: true,
      comparison_color_scheme: "Green",
      conditional_formatting: [],
      comparison_type: "values",
      dashboards: [74],
      extra_form_data: {
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
        ],
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
      },
      chart_id: 1120,
      label_colors: {},
      shared_label_colors: [],
      map_label_colors: {
        "COUNT(slot_score_category)": "#1FA8C9",
        "COUNT(content_score_category)": "#1FA8C9",
        "AVG(lead_in_score)": "#1FA8C9",
        "AVG(rvr_score)": "#454E7C",
        "AVG(wte_score)": "#5AC189",
        "AVG(content_score)": "#FF7F44",
        "AVG(arr_score)": "#666666",
        "AVG(reach_score)": "#E04355",
        "AVG(ovr_score)": "#FCC700",
      },
      extra_filters: [],
      force: false,
      result_format: "json",
      result_type: "full",
    },
    queries: [
      {
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
          {
            col: "date",
            op: "TEMPORAL_RANGE",
            val: "No filter",
          },
        ],
        extras: {
          having: "",
          where: "",
        },
        applied_time_extras: {},
        columns: ["program_name", "channel_name_tvd", "time_group", "week_day"],
        metrics: [
          {
            aggregate: null,
            column: null,
            datasourceWarning: false,
            expressionType: "SQL",
            hasCustomLabel: false,
            label: "count (*)",
            optionName: "metric_35sjruh9oj2_ugrwbdsdew",
            sqlExpression: "count (*)",
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "content_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4296,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(content_score)",
            optionName: "metric_kg0x0215sl_zup80jti3cp",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "wte_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4297,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(wte_score)",
            optionName: "metric_d4fh0nvmbj_b7rhslgjomv",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "rvr_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4300,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(rvr_score)",
            optionName: "metric_fq3ygbzf8bt_9gwgeqaxrk",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "ovr_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4299,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(ovr_score)",
            optionName: "metric_gbtswfejsts_z387kiaai9",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "arr_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4289,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(arr_score)",
            optionName: "metric_69lozuoyu2h_dczm2l8prht",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "tsv_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4301,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(tsv_score)",
            optionName: "metric_amtvfldi4k5_cbyc2td5cjw",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "slot_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4298,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(slot_score)",
            optionName: "metric_v1alya6m7at_9yo0pnhn8um",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "slot_rating_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4279,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(slot_rating_score)",
            optionName: "metric_pvvq9am6mh_6skk4uewiuf",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "slot_reach_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4273,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(slot_reach_score)",
            optionName: "metric_myl4u2rojyg_bi6c5zvv4o",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "lead_in_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4276,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(lead_in_score)",
            optionName: "metric_m46hytb8vh_276o9qe5a0v",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "lead_out_score",
              description: null,
              expression: null,
              filterable: true,
              groupby: true,
              id: 4277,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(lead_out_score)",
            optionName: "metric_ju95j2v9uy_8fduwyxvuti",
            sqlExpression: null,
          },
        ],
        orderby: [
          [
            {
              aggregate: "MAX",
              column: {
                advanced_data_type: null,
                changed_on: "2026-09-15T09:26:30.113179",
                column_name: "content_score",
                created_on: "2026-09-15T09:26:30.113176",
                description: null,
                expression: null,
                extra: '{"warning_markdown":null}',
                filterable: true,
                groupby: true,
                id: 8068,
                is_active: true,
                is_dttm: false,
                python_date_format: null,
                type: "DOUBLE",
                type_generic: 0,
                uuid: "5a521326-e932-4fb2-a435-43753ed5bf20",
                verbose_name: null,
              },
              datasourceWarning: false,
              expressionType: "SIMPLE",
              hasCustomLabel: false,
              label: "MAX(content_score)",
              optionName: "metric_sg01vgonb3_0uobtl8xpbr",
              sqlExpression: null,
            },
            true,
          ],
        ],
        annotation_layers: [],
        row_limit: 1000,
        series_limit: 0,
        series_limit_metric: {
          aggregate: "MAX",
          column: {
            advanced_data_type: null,
            changed_on: "2026-09-15T09:26:30.113179",
            column_name: "content_score",
            created_on: "2026-09-15T09:26:30.113176",
            description: null,
            expression: null,
            extra: '{"warning_markdown":null}',
            filterable: true,
            groupby: true,
            id: 8068,
            is_active: true,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            uuid: "5a521326-e932-4fb2-a435-43753ed5bf20",
            verbose_name: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "MAX(content_score)",
          optionName: "metric_sg01vgonb3_0uobtl8xpbr",
          sqlExpression: null,
        },
        order_desc: false,
        url_params: {
          native_filters_key:
            "tmn28MCp4l0hbde4xXiAQcE2Ix-3vQTxRFeT1mhRL_M-5SCotyce2HrvqcLILJvf",
        },
        custom_params: {},
        custom_form_data: {},
        post_processing: [],
        time_offsets: [],
      },
    ],
    result_format: "json",
    result_type: "full",
  },
};
