export const chart1121 = {
  url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A1121%7D&dashboard_id=74`,
  payload: {
    datasource: {
      id: 321,
      type: "table",
    },
    force: false,
    form_data: {
      adhoc_filters: [
        {
          clause: "WHERE",
          comparator: "No filter",
          expressionType: "SIMPLE",
          isExtra: true,
          operator: "TEMPORAL_RANGE",
          subject: "date",
        },
      ],
      annotation_layers: [],
      chart_id: 1121,
      color_scheme: "supersetColors",
      comparison_type: "values",
      dashboards: [],
      datasource: "321__table",
      extra_filters: [],
      extra_form_data: {
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
        ],
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
      },
      force: false,
      forecastInterval: 0.8,
      forecastPeriods: 10,
      groupby: [],
      label_colors: {},
      legendOrientation: "top",
      legendType: "scroll",
      map_label_colors: {
        "AVG(arr_score)": "#666666",
        "AVG(content_score)": "#FF7F44",
        "AVG(lead_in_score)": "#1FA8C9",
        "AVG(ovr_score)": "#FCC700",
        "AVG(reach_score)": "#E04355",
        "AVG(rvr_score)": "#454E7C",
        "AVG(wte_score)": "#5AC189",
        "COUNT(content_score_category)": "#1FA8C9",
        "COUNT(slot_score_category)": "#1FA8C9",
      },
      metrics: [
        {
          aggregate: "COUNT",
          column: {
            advanced_data_type: null,
            certification_details: null,
            certified_by: null,
            column_name: "slot_score_category",
            description: null,
            expression:
              "CASE \r\n    WHEN slot_score < 20 THEN '<20'\r\n    WHEN slot_score <35 THEN '20-34'\r\n    WHEN slot_score <50 THEN '35-49'\r\n    WHEN slot_score <65 THEN '50-64'\r\n    WHEN slot_score <80 THEN '65-79'\r\n    WHEN slot_score >= 80 THEN '>=80'\r\n    ELSE 'Unknown'\r\nEND",
            filterable: true,
            groupby: true,
            id: 8070,
            is_certified: false,
            is_dttm: false,
            python_date_format: null,
            type: null,
            type_generic: null,
            verbose_name: null,
            warning_markdown: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "COUNT(slot_score_category)",
          optionName: "metric_ko9q7vm0dqj_yxvjdhn2d8q",
          sqlExpression: null,
        },
      ],
      only_total: true,
      order_desc: true,
      orientation: "vertical",
      own_color_scheme: "supersetColors",
      result_format: "json",
      result_type: "full",
      rich_tooltip: true,
      row_limit: 10000,
      shared_label_colors: [],
      show_empty_columns: true,
      show_legend: true,
      showTooltipPercentage: true,
      showTooltipTotal: true,
      slice_id: 1121,
      sort_series_type: "sum",
      time_shift_color: true,
      tooltipTimeFormat: "smart_date",
      truncate_metric: true,
      truncateXAxis: true,
      url_params: {
        native_filters_key:
          "i1n-Sa6qDM6gfFWzlaDhzTj2XgDqWGqYO8skLct1pUvvu8tf6ZUGLs4b3O7q-LCx",
      },
      viz_type: "echarts_timeseries_bar",
      x_axis: "slot_score_category",
      x_axis_sort_asc: true,
      x_axis_sort_series: "name",
      x_axis_sort_series_ascending: true,
      x_axis_time_format: "smart_date",
      x_axis_title_margin: 15,
      y_axis_bounds: [null, null],
      y_axis_format: "SMART_NUMBER",
      y_axis_title_margin: 15,
      y_axis_title_position: "Left",
    },
    queries: [
      {
        annotation_layers: [],
        applied_time_extras: {},
        columns: [
          {
            columnType: "BASE_AXIS",
            expressionType: "SQL",
            label: "slot_score_category",
            sqlExpression: "slot_score_category",
          },
        ],
        custom_form_data: {},
        custom_params: {},
        extras: {
          having: "",
          where: "",
        },
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
          {
            col: "date",
            op: "TEMPORAL_RANGE",
            val: "No filter",
          },
        ],
        metrics: [
          {
            aggregate: "COUNT",
            column: {
              advanced_data_type: null,
              certification_details: null,
              certified_by: null,
              column_name: "slot_score_category",
              description: null,
              expression:
                "CASE \r\n    WHEN slot_score < 20 THEN '<20'\r\n    WHEN slot_score <35 THEN '20-34'\r\n    WHEN slot_score <50 THEN '35-49'\r\n    WHEN slot_score <65 THEN '50-64'\r\n    WHEN slot_score <80 THEN '65-79'\r\n    WHEN slot_score >= 80 THEN '>=80'\r\n    ELSE 'Unknown'\r\nEND",
              filterable: true,
              groupby: true,
              id: 8070,
              is_certified: false,
              is_dttm: false,
              python_date_format: null,
              type: null,
              type_generic: null,
              verbose_name: null,
              warning_markdown: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "COUNT(slot_score_category)",
            optionName: "metric_ko9q7vm0dqj_yxvjdhn2d8q",
            sqlExpression: null,
          },
        ],
        order_desc: true,
        orderby: [
          [
            {
              aggregate: "COUNT",
              column: {
                advanced_data_type: null,
                certification_details: null,
                certified_by: null,
                column_name: "slot_score_category",
                description: null,
                expression:
                  "CASE \r\n    WHEN slot_score < 20 THEN '<20'\r\n    WHEN slot_score <35 THEN '20-34'\r\n    WHEN slot_score <50 THEN '35-49'\r\n    WHEN slot_score <65 THEN '50-64'\r\n    WHEN slot_score <80 THEN '65-79'\r\n    WHEN slot_score >= 80 THEN '>=80'\r\n    ELSE 'Unknown'\r\nEND",
                filterable: true,
                groupby: true,
                id: 8070,
                is_certified: false,
                is_dttm: false,
                python_date_format: null,
                type: null,
                type_generic: null,
                verbose_name: null,
                warning_markdown: null,
              },
              datasourceWarning: false,
              expressionType: "SIMPLE",
              hasCustomLabel: false,
              label: "COUNT(slot_score_category)",
              optionName: "metric_ko9q7vm0dqj_yxvjdhn2d8q",
              sqlExpression: null,
            },
            false,
          ],
        ],
        post_processing: [
          {
            operation: "pivot",
            options: {
              aggregates: {
                "COUNT(slot_score_category)": {
                  operator: "mean",
                },
              },
              columns: [],
              drop_missing_columns: false,
              index: ["slot_score_category"],
            },
          },
          {
            operation: "flatten",
          },
        ],
        row_limit: 10000,
        series_columns: [],
        series_limit: 0,
        time_offsets: [],
        time_range: "2026-01-26T00:00:00 : 2026-01-31T00:00:00",
        url_params: {
          native_filters_key:
            "i1n-Sa6qDM6gfFWzlaDhzTj2XgDqWGqYO8skLct1pUvvu8tf6ZUGLs4b3O7q-LCx",
        },
      },
    ],
    result_format: "json",
    result_type: "full",
  },
};
