export const chart1125 = {
  url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A1125%7D&dashboard_id=74`,
  payload: {
    datasource: {
      id: 326,
      type: "table",
    },
    force: false,
    form_data: {
      adhoc_filters: [
        {
          clause: "WHERE",
          comparator: ["Total"],
          datasourceWarning: false,
          expressionType: "SIMPLE",
          filterOptionName: "filter_b01tfw9e058_0i327krma56k",
          isExtra: false,
          isNew: false,
          operator: "IN",
          operatorId: "IN",
          sqlExpression: null,
          subject: "platform",
        },
        {
          clause: "WHERE",
          comparator: "No filter",
          expressionType: "SIMPLE",
          operator: "TEMPORAL_RANGE",
          subject: "date",
        },
      ],
      all_columns: [],
      allow_render_html: true,
      chart_id: 1125,
      color_pn: true,
      comparison_color_scheme: "Green",
      comparison_type: "values",
      conditional_formatting: [],
      dashboards: [74],
      datasource: "326__table",
      extra_filters: [],
      extra_form_data: {
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
        ],
        time_range: "2026-01-01T00:00:00 : 2026-01-01T00:00:00",
      },
      force: false,
      groupby: ["block", "channel_name_tvd", "week_day"],
      include_search: true,
      label_colors: {},
      map_label_colors: {
        "COUNT(content_score_category)": "#1FA8C9",
        "COUNT(slot_score_category)": "#1FA8C9",
      },
      metrics: [
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            changed_on: "2026-09-24T05:02:05.061298",
            column_name: "block_score",
            created_on: "2026-09-24T05:02:05.061294",
            description: null,
            expression:
              "block_rating_score * 0.25 + block_reach_score * 0.25 + block_bor_score * 0.25 + block_brr_score * 0.25",
            extra: "{}",
            filterable: true,
            groupby: true,
            id: 4560,
            is_active: true,
            is_dttm: false,
            python_date_format: null,
            type: null,
            type_generic: null,
            uuid: "f581f3ac-e7ff-435f-89a8-de36dd9c70aa",
            verbose_name: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(block_score)",
          optionName: "metric_5zk81aj5h2c_qzy2yaex189",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            changed_on: "2026-09-24T04:54:21.234198",
            column_name: "block_rating_score",
            created_on: "2026-09-24T04:54:21.234197",
            description: null,
            expression: null,
            extra: '{"warning_markdown":null}',
            filterable: true,
            groupby: true,
            id: 4552,
            is_active: true,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            uuid: "68c7b349-f3f2-4486-895b-1e260232869e",
            verbose_name: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(block_rating_score)",
          optionName: "metric_v8om8uvw8k_9zpn9jk7c95",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            changed_on: "2026-09-24T04:54:21.233935",
            column_name: "block_rating",
            created_on: "2026-09-24T04:54:21.233934",
            description: null,
            expression: null,
            extra: '{"warning_markdown":null}',
            filterable: true,
            groupby: true,
            id: 4533,
            is_active: true,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            uuid: "2d2d8542-aeee-4b5f-8793-d1a8c3e72d71",
            verbose_name: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(block_rating)",
          optionName: "metric_r2qppyw4e9l_tfmwm7yda0p",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            changed_on: "2026-09-24T04:54:21.234170",
            column_name: "block_reach_score",
            created_on: "2026-09-24T04:54:21.234169",
            description: null,
            expression: null,
            extra: '{"warning_markdown":null}',
            filterable: true,
            groupby: true,
            id: 4550,
            is_active: true,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            uuid: "204c8f5e-b97c-47e5-975f-847093bab098",
            verbose_name: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(block_reach_score)",
          optionName: "metric_ljwciiop82f_w8m6t8o2thm",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            changed_on: "2026-09-24T04:54:21.233907",
            column_name: "total_unique_viewers",
            created_on: "2026-09-24T04:54:21.233906",
            description: null,
            expression: null,
            extra: '{"warning_markdown":null}',
            filterable: true,
            groupby: true,
            id: 4531,
            is_active: true,
            is_dttm: false,
            python_date_format: null,
            type: "BIGINT",
            type_generic: 0,
            uuid: "dabe7946-a6c7-41ed-a8d1-a492c2167e2c",
            verbose_name: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(total_unique_viewers)",
          optionName: "metric_9lrewhktgt_fz7k9ivatxt",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            changed_on: "2026-09-24T04:54:21.234254",
            column_name: "block_bor_score",
            created_on: "2026-09-24T04:54:21.234253",
            description: null,
            expression: null,
            extra: '{"warning_markdown":null}',
            filterable: true,
            groupby: true,
            id: 4556,
            is_active: true,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            uuid: "8ba9c03a-4e1c-4e02-81e7-b4deb24cb648",
            verbose_name: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(block_bor_score)",
          optionName: "metric_qhboyqoup8e_b4wjg0rehul",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            changed_on: "2026-09-24T04:54:21.233988",
            column_name: "block_organic_rate",
            created_on: "2026-09-24T04:54:21.233987",
            description: null,
            expression: null,
            extra: '{"warning_markdown":null}',
            filterable: true,
            groupby: true,
            id: 4537,
            is_active: true,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            uuid: "85d2214c-7ffc-4334-9f63-13b69031eb3f",
            verbose_name: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(block_organic_rate)",
          optionName: "metric_ej37556vn16_2z4oz2gga4",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            changed_on: "2026-09-24T04:54:21.234227",
            column_name: "block_brr_score",
            created_on: "2026-09-24T04:54:21.234226",
            description: null,
            expression: null,
            extra: '{"warning_markdown":null}',
            filterable: true,
            groupby: true,
            id: 4554,
            is_active: true,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            uuid: "f8161d89-abed-4ed8-98d1-70024ebc3762",
            verbose_name: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(block_brr_score)",
          optionName: "metric_n0f6gwtphyi_m7nf8f6tow",
          sqlExpression: null,
        },
        {
          aggregate: "AVG",
          column: {
            advanced_data_type: null,
            changed_on: "2026-09-24T04:54:21.233961",
            column_name: "block_return_rate",
            created_on: "2026-09-24T04:54:21.233960",
            description: null,
            expression: null,
            extra: '{"warning_markdown":null}',
            filterable: true,
            groupby: true,
            id: 4535,
            is_active: true,
            is_dttm: false,
            python_date_format: null,
            type: "DOUBLE",
            type_generic: 0,
            uuid: "16279fc0-b908-4483-981d-197dd8f7705d",
            verbose_name: null,
          },
          datasourceWarning: false,
          expressionType: "SIMPLE",
          hasCustomLabel: false,
          label: "AVG(block_return_rate)",
          optionName: "metric_pdew0fyf0i_uzimhz6ggon",
          sqlExpression: null,
        },
      ],
      order_by_cols: [],
      order_desc: true,
      percent_metrics: [],
      query_mode: "aggregate",
      result_format: "json",
      result_type: "full",
      row_limit: 1000,
      server_page_length: 10,
      shared_label_colors: [],
      show_cell_bars: true,
      slice_id: 1125,
      table_timestamp_format: "smart_date",
      temporal_columns_lookup: {
        date: true,
      },
      url_params: {
        native_filters_key:
          "lGISjkeISJV8fH_ImZpAoed6ow60Zz45i6fa8pUcHWB-Sxl8bstaGR-GDVPf2xnr",
      },
      viz_type: "table",
    },
    queries: [
      {
        annotation_layers: [],
        applied_time_extras: {},
        columns: ["block", "channel_name_tvd", "week_day"],
        custom_form_data: {},
        custom_params: {},
        extras: {
          having: "",
          where: "",
        },
        filters: [
          {
            col: "channel_name_tvd",
            op: "IN",
            val: ["VTV1"],
          },
          {
            col: "platform",
            op: "IN",
            val: ["Total"],
          },
          {
            col: "date",
            op: "TEMPORAL_RANGE",
            val: "No filter",
          },
        ],
        metrics: [
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              changed_on: "2026-09-24T05:02:05.061298",
              column_name: "block_score",
              created_on: "2026-09-24T05:02:05.061294",
              description: null,
              expression:
                "block_rating_score * 0.25 + block_reach_score * 0.25 + block_bor_score * 0.25 + block_brr_score * 0.25",
              extra: "{}",
              filterable: true,
              groupby: true,
              id: 4560,
              is_active: true,
              is_dttm: false,
              python_date_format: null,
              type: null,
              type_generic: null,
              uuid: "f581f3ac-e7ff-435f-89a8-de36dd9c70aa",
              verbose_name: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(block_score)",
            optionName: "metric_5zk81aj5h2c_qzy2yaex189",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              changed_on: "2026-09-24T04:54:21.234198",
              column_name: "block_rating_score",
              created_on: "2026-09-24T04:54:21.234197",
              description: null,
              expression: null,
              extra: '{"warning_markdown":null}',
              filterable: true,
              groupby: true,
              id: 4552,
              is_active: true,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              uuid: "68c7b349-f3f2-4486-895b-1e260232869e",
              verbose_name: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(block_rating_score)",
            optionName: "metric_v8om8uvw8k_9zpn9jk7c95",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              changed_on: "2026-09-24T04:54:21.233935",
              column_name: "block_rating",
              created_on: "2026-09-24T04:54:21.233934",
              description: null,
              expression: null,
              extra: '{"warning_markdown":null}',
              filterable: true,
              groupby: true,
              id: 4533,
              is_active: true,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              uuid: "2d2d8542-aeee-4b5f-8793-d1a8c3e72d71",
              verbose_name: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(block_rating)",
            optionName: "metric_r2qppyw4e9l_tfmwm7yda0p",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              changed_on: "2026-09-24T04:54:21.234170",
              column_name: "block_reach_score",
              created_on: "2026-09-24T04:54:21.234169",
              description: null,
              expression: null,
              extra: '{"warning_markdown":null}',
              filterable: true,
              groupby: true,
              id: 4550,
              is_active: true,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              uuid: "204c8f5e-b97c-47e5-975f-847093bab098",
              verbose_name: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(block_reach_score)",
            optionName: "metric_ljwciiop82f_w8m6t8o2thm",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              changed_on: "2026-09-24T04:54:21.233907",
              column_name: "total_unique_viewers",
              created_on: "2026-09-24T04:54:21.233906",
              description: null,
              expression: null,
              extra: '{"warning_markdown":null}',
              filterable: true,
              groupby: true,
              id: 4531,
              is_active: true,
              is_dttm: false,
              python_date_format: null,
              type: "BIGINT",
              type_generic: 0,
              uuid: "dabe7946-a6c7-41ed-a8d1-a492c2167e2c",
              verbose_name: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(total_unique_viewers)",
            optionName: "metric_9lrewhktgt_fz7k9ivatxt",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              changed_on: "2026-09-24T04:54:21.234254",
              column_name: "block_bor_score",
              created_on: "2026-09-24T04:54:21.234253",
              description: null,
              expression: null,
              extra: '{"warning_markdown":null}',
              filterable: true,
              groupby: true,
              id: 4556,
              is_active: true,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              uuid: "8ba9c03a-4e1c-4e02-81e7-b4deb24cb648",
              verbose_name: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(block_bor_score)",
            optionName: "metric_qhboyqoup8e_b4wjg0rehul",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              changed_on: "2026-09-24T04:54:21.233988",
              column_name: "block_organic_rate",
              created_on: "2026-09-24T04:54:21.233987",
              description: null,
              expression: null,
              extra: '{"warning_markdown":null}',
              filterable: true,
              groupby: true,
              id: 4537,
              is_active: true,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              uuid: "85d2214c-7ffc-4334-9f63-13b69031eb3f",
              verbose_name: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(block_organic_rate)",
            optionName: "metric_ej37556vn16_2z4oz2gga4",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              changed_on: "2026-09-24T04:54:21.234227",
              column_name: "block_brr_score",
              created_on: "2026-09-24T04:54:21.234226",
              description: null,
              expression: null,
              extra: '{"warning_markdown":null}',
              filterable: true,
              groupby: true,
              id: 4554,
              is_active: true,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              uuid: "f8161d89-abed-4ed8-98d1-70024ebc3762",
              verbose_name: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(block_brr_score)",
            optionName: "metric_n0f6gwtphyi_m7nf8f6tow",
            sqlExpression: null,
          },
          {
            aggregate: "AVG",
            column: {
              advanced_data_type: null,
              changed_on: "2026-09-24T04:54:21.233961",
              column_name: "block_return_rate",
              created_on: "2026-09-24T04:54:21.233960",
              description: null,
              expression: null,
              extra: '{"warning_markdown":null}',
              filterable: true,
              groupby: true,
              id: 4535,
              is_active: true,
              is_dttm: false,
              python_date_format: null,
              type: "DOUBLE",
              type_generic: 0,
              uuid: "16279fc0-b908-4483-981d-197dd8f7705d",
              verbose_name: null,
            },
            datasourceWarning: false,
            expressionType: "SIMPLE",
            hasCustomLabel: false,
            label: "AVG(block_return_rate)",
            optionName: "metric_pdew0fyf0i_uzimhz6ggon",
            sqlExpression: null,
          },
        ],
        order_desc: true,
        orderby: [
          [
            {
              aggregate: "AVG",
              column: {
                advanced_data_type: null,
                changed_on: "2026-09-24T05:02:05.061298",
                column_name: "block_score",
                created_on: "2026-09-24T05:02:05.061294",
                description: null,
                expression:
                  "block_rating_score * 0.25 + block_reach_score * 0.25 + block_bor_score * 0.25 + block_brr_score * 0.25",
                extra: "{}",
                filterable: true,
                groupby: true,
                id: 4560,
                is_active: true,
                is_dttm: false,
                python_date_format: null,
                type: null,
                type_generic: null,
                uuid: "f581f3ac-e7ff-435f-89a8-de36dd9c70aa",
                verbose_name: null,
              },
              datasourceWarning: false,
              expressionType: "SIMPLE",
              hasCustomLabel: false,
              label: "AVG(block_score)",
              optionName: "metric_5zk81aj5h2c_qzy2yaex189",
              sqlExpression: null,
            },
            false,
          ],
        ],
        post_processing: [],
        row_limit: 1000,
        series_limit: 0,
        time_offsets: [],
        time_range: "2026-01-01T00:00:00 : 2026-01-01T00:00:00",
        url_params: {
          native_filters_key:
            "lGISjkeISJV8fH_ImZpAoed6ow60Zz45i6fa8pUcHWB-Sxl8bstaGR-GDVPf2xnr",
        },
      },
    ],
    result_format: "json",
    result_type: "full",
  },
};
